server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/reserva_hotel
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true